spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.2:3306/Telco_Customer?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate: 
      ddl-auto: update
